version: "3.9"

services:
  app:
    depends_on:
      - mongodb
    build: ./app
    ports:
      - 3000:3000
    environment:
      DB_HOST: "mongodb"
      DB_USER: $MONGODB_USER
      DB_PASSWORD: $MONGODB_PASSWORD
      DB_DATABASE: $MONGODB_DATABASE
      DB_PORT: 27017

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    restart: always
    ports: 
      - 27016:27017
    volumes:
      - db:/data/db

volumes:
  db:
